#! /bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin

set -e

if [ -e /etc/cron.daily/boa ]; then
  echo 'conffile /etc/cron.daily/boa exists.  New functionality is in /etc/logrotate.d/boa.'
  if test `md5sum /etc/cron.daily/boa | awk '{print $1}'` = '5e05937798a45a32ed7bf03e596d1427'; then
    echo '/etc/cron.daily/boa not modified -- Removing /etc/cron.daily/boa'
    rm -f /etc/cron.daily/boa
  else
    echo '/etc/cron.daily/boa modified -- Moving to /etc/cron.daily/boa.obsolete'
    mv -f /etc/cron.daily/boa /etc/cron.daily/boa.obsolete
  fi
fi

#DEBHELPER#

exit 0