#! /bin/sh

if [ -x "/etc/init.d/boa" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
        	invoke-rc.d boa stop || exit $?
        else
              	/etc/init.d/boa stop || exit $?
        fi
fi

#DEBHELPER#
