/* escape.h
 *  automatically generated by escape.pl
 *  this version suited for 32 bit machines
 *  Not copyrighted, given its size and machine-generated nature
 *
 *  defines the macro needs_escape(c), which returns non-zero when c
 *  needs escaping according to RFC-1738 section 2.2.
*/

#ifndef __NEEDS_ESCAPE__
#define __NEEDS_ESCAPE__

unsigned long _needs_escape[8] = {
    0xffffffffL, 0x780000fdL, 0x78000001L, 0xb8000001L, 0xffffffffL,
    0xffffffffL, 0xffffffffL, 0xffffffffL
};
#define needs_escape(c) (_needs_escape[(c)>>5]&(1<<((c)&31)))
#endif
